#H2 config
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
#        show_sql: true

logging:
  level:
    org.hibernate.sql: debug
